### ISSUE TITLE
led strip not working with linux target (IEC-226)

### ISSUE THREAD

**Issue by MJAS1** [espressif/idf-extra-components#433]
### Answers checklist.

- [X] I have read the component documentation [ESP-IDF Components](https://components.espressif.com) and the issue is not addressed there.
- [X] I am using target and esp-idf version as defined in component's idf_component.yml
- [X] I have searched the [issue tracker](https://github.com/espressif/idf-extra-components/issues?q=is%3Aissue) for a similar issue and not found any related issue.

### Which component are you using? If you choose Other, provide details in More Information.

led_strip

### ESP-IDF version.

v5.3.1

### Development Kit.

linux

### Used Component version.

2.5.5

### More Information.

Trying to run unit tests with a project using led_strip in linux target causes error:

```
fatal error: driver/spi_master.h: No such file or directory
BUG: component_requirements.py: driver/spi_master.h found in component esp_driver_spi which is already in the requirements list of espressif__led_strip
```

This problem can be reproduced easily with an empty project and adding led_strip as a dependency:
```
idf.py create-project test
cd test
idf.py add-dependency "led_strip^2.5.5"
idf.py --preview set-target linux
idf.py build
```

**Comment by fhrbata** [comment]
Hello @MJAS1 ,

the `esp_driver_spi` is not supported on `linux` target, please see https://github.com/espressif/esp-idf/blob/v5.3.1/components/esp_driver_spi/CMakeLists.txt#L4. The hint message(BUG) is misleading, probably because 5.3.1 is missing https://github.com/espressif/esp-idf/commit/fbe8bf89ee4431c72631bc227bf7008cb3aa024e. I believe this is similar issue to https://github.com/espressif/esp-idf/issues/13447.

Thank you

**Comment by MJAS1** [comment]
Alright, thanks for explaining
